import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      fontFamily: {
        alexBrush: ["AlexBrush", "sans-serif"],
        anybody: ["Anybody", "sans-serif"],
        bagnardSans: ["BagnardSans", "sans-serif"],
        brolimo: ["Brolimo", "sans-serif"],
        cabinetGrotesk: ["cabinetGrotesk", "sans-serif"],
        casta: ["Casta", "sans-serif"],
        cinzel: ["Cinzel", "serif"],
        clashDisplay: ["ClashDisplay", "sans-serif"],
        droidSans: ["DroidSans", "monospace"],
        excon: ["Excon", "sans-serif"],
        highrise: ["Highrise", "sans-serif"],
        fira: ["Fira", "monospace"],
        inconsolata: ["Inconsolata", "monospace"],
        inter: ["Inter", "sans-serif"],
        leagueScript: ["LeagueScript", "cursive"],
        leagueMono: ["LeagueMono", "monospace"],
        leagueSpartan: ["LeagueSpartan", "sans-serif"],
        lemonMilk: ["LemonMilk", "sans-serif"],
        lindenHill: ["LindenHill", "serif"],
        majorMono: ["MajorMono", "monospace"],
        manrope: ["Manrope", "sans-serif"],
        melodrama: ["Melodrama", "serif"],
        montserrat: ["Montserrat", "sans-serif"],
        leMurmure: ["le-Murmure", "sans-serif"],
        muscularStrength: ["MuscularStrength", "sans-serif"],
        openSans: ["OpenSans", "sans-serif"],
        orbitron: ["Orbitron", "sans-serif"],
        outward: ["Outward", "sans-serif"],
        pencerio: ["Pencerio", "sans-serif"],
        prociono: ["Prociono", "serif"],
        pilowlava: ["Pilowlava", "sans-serif"],
        ptMono: ["PTMono", "monospace"],
        raleway: ["Raleway", "sans-serif"],
        ranade: ["Ranade", "serif"],
        redHat: ["RedHat", "sans-serif"],
        rokkitt: ["Rokkitt", "serif"],
        satoshi: ["Satoshi", "sans-serif"],
        skyscapers: ["Skyscapers", "sans-serif"],
        soria: ["Soria", "serif"],
        vercetti: ["Vercetti", "sans-serif"],
        wangi: ["Wangi", "sans-serif"],
        workSans: ["WorkSans", "sans-serif"],
        yatra: ["Yatra", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
